### ISSUE TITLE
Payout endpoint data 

### ISSUE THREAD

**Issue by grafael** [storj/stats#17]
The payout (daily) endpoint seems off when compared against monthly payments.

AC: Review all rates and payouts values

**Comment by grafael** [comment]
Check endpoint here: https://stats.storjshare.io/

**Comment by stoweandi** [comment]
Note: data we have here doesn't match with what we have in stripe

**Comment by stoweandi** [comment]
@iglesiasbrandon is this still a relevant endpoint? 
We do not disclose this endpoint to the community. 
If you don't want to disclose this end point to the community, we can just remove this endpoint.

**Comment by NiaStorj** [comment]
@iglesiasbrandon please see the question above and provide a comment

**Comment by iglesiasbrandon** [comment]
@grafael @stoweandi @NiaStorj this endpoint is used for the web3 index

https://github.com/web3index/web3index-org/pull/76/files

https://stats.storjshare.io/payout.json

We discussed updating this endpoint to include some more information because it's not currently accurate. It's also not accurately named; this endpoint is node payout data. 

We need to update this endpoint because it is not accurate with what we pay out to nodes each month. 
https://storj.slack.com/archives/C01D98FG7UM/p1657293036317549

**Comment by NiaStorj** [comment]
@shaupt131  @stoweandi see Brandon's comments above

**Comment by grafael** [comment]
@iglesiasbrandon , I have updated the query that generates https://stats.storjshare.io/payout.json 

I have also created a query https://redash.datasci.storj.io/queries/3435/source to validate the daily data. This query compares the sum of daily payouts against the month's payout for validation purposes. However, please note that the current month's data is an estimation due to possible occurrences like new node additions, node disqualifications, and other factors.

If you come across any anomalies in this new endpoint data, please inform me.

**Comment by iglesiasbrandon** [comment]
awesome, thank you @grafael
