### ISSUE TITLE
Better Anonymisation of Geolocation data

### ISSUE THREAD

**Issue by GollyTicker** [storj/stats#20]
Hi everyone,

While I enjoy seeing the visualisation of the storj network, I noticed, that the geo-location data may be revealing a bit too much by my taste. Based on the data provided in by this repository, the map on https://storjnet.info is quite detailed. One can actually zoom into the map and *see the estimated geo-location down to the exact house/building*.

I think, this is too preise and such detailed information shouldn't be publicly available. I am also not sure, whether it strictly speaking conforms to EU-GDPR. (It is anonymized, so taht's good. But in certain rural areas its a different thing...)

Here is how it looks like for a place in Tokyo near center city:
![image](https://user-images.githubusercontent.com/4527862/212468403-25dc0ec3-1ba3-4d4b-802e-212e090b0cc7.png)

I think the main point of the geo-location data is to give an idea of how decentralised and distributed the nodes are running physically. This can be done while increasing the privacy, by randomly perturbing the location (e.g. ~500m in any direction) or by only providing an approximate region of say a few square kilometers (by making a more coarse-grained grid of buckets).

That's just a suggestion from my side. What do you think?

I am aware, that this would be a breaking change - but I think in the long term, this is better so. Alternatively, one could always just randomly perturn the location. But then, the pertubation needs to stay the same for the same node always, as otherwise one could figure out the location by averaging the nearby positions.

**Comment by kaloyan-raev** [comment]
Storj does not collect any geolocation data from the storage node operator. The geolocation is estimated from the IP address the storage node operator participates in the Storj network. The IP address is public info. Otherwise, no one could upload or download data from the storage nodes.

The map on https://storjnet.info/ existed long before Storj started to publish network stats. They've done this by scraping the IP addresses of storage nodes and mapping them using publicly available IP2Geo databases.

Therefore, the geolocation data we publish with our network stats is no new information. The geolocation is as precise as the public IP2Geo databases are precise. From my own experience, these databases are inaccurate. For example, I don't see a dot on the map where my home is located, although I run a storage node there.

**Comment by GollyTicker** [comment]
Thank you for your time and your response.

> Storj does not collect any geolocation data from the storage node operator. The geolocation is estimated from the IP address the storage node operator participates in the Storj network.

Good point. I had forgotten this aspect ^^' It makes sense, that the data collectors are simply combining and aggregating publicly available knowledge.

I'm closing this then, as the IP addresses are not precise.
