### ISSUE TITLE
nodes.json returning object not found

### ISSUE THREAD

**Issue by CutieePie-bit** [storj/stats#25]
When calling the JSON API endpoint https://stats.storjshare.io/nodes.json

Started getting an object not found error.

Also nodes_geo.json is returning the same object not found.

**Comment by ifraixedes** [comment]
It’s fixed now.

We weren’t aware of an issue in our infrastructure that generates the stats JSON files.

The nodes_geo.json is still unavailable because it’s generated every 24 hours, it will be available the next time the task executes.

I will leave the issue open until then.

Thanks for reporting it.

**Comment by ifraixedes** [comment]
`nodes_geo.json` is back as expected
